name: PR checks

on:
  pull_request:

jobs:
  code_checks:
    uses: ./.github/workflows/_code_checks.yml

  pr_title_check:
    runs-on: ubuntu-latest
    name: Check PR title
    steps:
    - name: check_title
      uses: Slashgear/action-check-pr-title@v3.0.0
      with:
        regexp: '^((\[MAJOR\])|(\[MINOR\])|(\[PATCH\])).+$'
