# taken and adapted from:
# https://github.com/joaomcteixeira/python-project-skeleton/blob/master/.github/workflows/version-bump-and-package.yml
name: Version bump

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'

jobs:
  code_checks:
    uses: ./.github/workflows/_code_checks.yml

  version_bump:
    runs-on: ubuntu-latest
    needs: code_checks
    steps:

    - name: Check commit message
      if: |
        (!startsWith(github.event.head_commit.message, '[MAJOR]')) &&
        (!startsWith(github.event.head_commit.message, '[MINOR]')) &&
        (!startsWith(github.event.head_commit.message, '[PATCH]'))
      run: exit 1

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Setup Git
      run: |
        git config user.name "version_bump"
        git config user.email 'bipboup@imabot.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_PERSONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version

    - name: Bump Major Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version major
      if: startsWith(github.event.head_commit.message, '[MAJOR]')

    - name: Bump Minor Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version minor
      if: startsWith(github.event.head_commit.message, '[MINOR]')

    - name: Bump Patch Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version patch
      if: startsWith(github.event.head_commit.message, '[PATCH]')

    - name: Commit version change to main
      run: |
        git push --follow-tags
